services:
  admin-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    env_file:
      - AdmineTetoToys.Api/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: "8081"
      CorsOrigin: http://localhost:4201
      Redis__Host: shared_redis
      Redis__Port: ${Redis__Port:-6379}
      MySQL__Server: shared_mysql
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - infrastructure_network

networks:
  infrastructure_network:
    external: true
